# Generated by Django 5.0.7 on 2024-07-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='goals',
            field=models.IntegerField(default=0, help_text='목표 시간을 분 단위로 입력해주세요'),
        ),
    ]
