# Generated by Django 5.0.7 on 2024-08-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("naverocr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload_image",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
