# Generated by Django 5.0.7 on 2024-08-03 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='relationship.Relationship', to=settings.AUTH_USER_MODEL, verbose_name='팔로우 중인 사용자들'),
        ),
    ]
