# Generated by Django 5.0.7 on 2024-08-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_customuser_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="top_apps",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_screentimes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
