# Generated by Django 5.0.7 on 2024-08-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_customuser_following_delete_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="top_apps",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
