# Generated by Django 5.0.7 on 2024-08-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_customuser_top_apps"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="total_screentimes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
